### ISSUE TITLE
Primeiro exercício

### ISSUE THREAD

**Issue by Luana-Leticia** [reprograma/on6-xp-s3-logica-js#2]
Oi. No primeiro exercício, a gente cria uma função que recebe a temperatura que o usuário digita e outra que faz a conversão? E a função que recebe a temperatura chama a função que converte? Fiquei com dúvida na interpretação da questão. Obrigada desde já =)

**Comment by isabellegalvao** [comment]
Pode ser do jeito que fizer sentido pra vc, não tem uma regra de onde usar a função.
