### ISSUE TITLE
Problemas ao rodar os exercícios da aula com o readline

### ISSUE THREAD

**Issue by camilabulcao** [reprograma/on6-xp-s3-logica-js#8]
Olá, estava fazendo as primeiras atividades dada em aula com o switch case, e estou com um problema:
C:\WINDOWS\system32\cmd.exe[3284]: c:\ws\src\node_file.cc:1658: Assertion `(argc) == (5)' failed.

O código ta certinho, já conferir aqui e tudo e nada quer rodar com a solicitação ao usuário. Já não sei o que fazer, pesquisei mas não encontrei nada claro como resolver e que eu tenha entendido.

**Comment by isabellegalvao** [comment]
Precisaria ver o seu código pra poder entender melhor
